AllCops:
  DisplayCopNames: true

StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/For:
  Enabled: false

# ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

# 条件式の方を意識させたい場合には後置の if/unless を使わない方が分かりやすい
Style/IfUnlessModifier:
  Enabled: false

# 30 まではギリギリ許せる範囲だった
Metrics/AbcSize:
  Enabled: false

# 6 は強すぎるので緩める
Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
